### ISSUE TITLE
fatal error: bits/c++config.h: No such file or directory

### ISSUE THREAD

**Issue by sumit-walia** [marg-tools/FN-CACTI#1]
Hi, I tried building fn-cacti but got the following error:

> /usr/include/c++/10/bits/stl_algobase.h:59:10: fatal error: bits/c++config.h: No such file or directory
   59 | #include <bits/c++config.h>

Tried multiple hacks to resolve this but couldn't. Please let me know how to resolve the issue.

**Comment by divyapraneetha** [comment]
Hi Sumit,

Could you please check gcc version. 
https://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit

The error source "#include <bits/c++config.h>" doesn't seem to be part of FN-CACTI code.

**Comment by divyapraneetha** [comment]
Hi Sumit,

Hope you have fixed the issue.

Else, follow the below answer:

Update the following lines in cacti.mk to -m64 flag to compile on 64-bit machine.
CXX = g++ -m64
CC  = gcc -m64
